### ISSUE TITLE
Missing music file in GitHub

### ISSUE THREAD

**Issue by esaiaswt** [Dark-Abyssal/Project_Snake#6]
Here is the error:
Traceback (most recent call last):
  File "c:\Users\esaia\OneDrive\Documents\projects\Project_Snake-1\Project Snake.py", line 21, in <module>
    mixer.music.load('Music File/music background.mp3')
pygame.error: No file 'Music File/music background.mp3' found in working directory 'C:\Users\esaia\OneDrive\Documents\projects\Project_Snake-1'.

**Comment by Kurarensu19** [comment]
Error should be corrected, music file has been added
