### ISSUE TITLE
Error when running code

### ISSUE THREAD

**Issue by esaiaswt** [Dark-Abyssal/Project_Snake#8]
Below is the error after git clone and run. Please resolve:
PS C:\Users\esaia\OneDrive\Documents\sdp_projects\Project_Snake> & C:/Users/esaia/anaconda3/envs/testAI/python.exe "c:/Users/esaia/OneDrive/Documents/sdp_projects/Project_Snake/Project Snake.py"
pygame 2.6.0 (SDL 2.28.4, Python 3.10.8)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\Users\esaia\OneDrive\Documents\sdp_projects\Project_Snake\Project Snake.py", line 4, in <module>
    import pygame_menu
ModuleNotFoundError: No module named 'pygame_menu'

**Comment by Kurarensu19** [comment]
Unsure why this is the case, perhaps you are missing something from the requirements file?
Tested on both Mr Sarzwan's and my team member's laptops and they work fine.
